name: Update Malayalam Trolls Gallery

on:
  schedule:
   # - cron: "*/15 * * * *"  # every 15 minutes
  #workflow_dispatch:

jobs:
  update-gallery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests PyGithub

      - name: Fetch images from Telegram
        run: python fetch_from_telegram.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Update manifest
        run: python generate_manifest.py
        env:
          GH_PAT: ${{ secrets.GH_PAT }}